### ISSUE TITLE
how can i re-activate the scanner?

### ISSUE THREAD

**Issue by hasgar** [shifeng1993/react-native-qr-scanner#1]
After one qr scan is done nothing happening, is there any option to re-active scanner again ?
if no please add that

**Comment by seeya** [comment]
I did it this way.
Set a parameter key in the declaration of your component like this:
```
<QRScannerView key={this.state.key} onRead={this.onRead} torchMode={false} hintText="Scan QR code"/>
```

Then upon scanning the value, increment the key count to another number. This will re-render the component.

```
onRead = ({data}) => {
    this.setState({
      key: this.state.key + 1
    });
  }
```

**Comment by shifeng1993** [comment]
1.2.2 版本已添加，此类问题会在三日后关闭
