### ISSUE TITLE
install的react-native-qr-scanner，里面没有QRreader，识别图中二维码的方法呀

### ISSUE THREAD

**Issue by weijing9035** [shifeng1993/react-native-qr-scanner#14]
install的react-native-qr-scanner，里面没有QRreader，识别图中二维码的方法呀，可否发一个全的出来，谢谢。
文档里面有这方法，但是下载下来的里面没有这个QRreader识别的代码。
需要识别图中二维码的功能。 @shifeng1993

**Comment by shifeng1993** [comment]
请仔细阅读文档
