### ISSUE TITLE
怎么扫描一次后，就不能再扫了（再也不回调onRead）？

### ISSUE THREAD

**Issue by SugarMilk** [shifeng1993/react-native-qr-scanner#6]
`
onRead = function(result) {
    let content = result.data;

    Alert.alert("扫描结果", content, [
        {text: '取消', onPress: this.userCanceled},
        {text: '确定', onPress: this.userConfirmed}
      ], {cancelable: true}
    );
`

**Comment by shifeng1993** [comment]
这是防止扫描重复触发的，销毁组件后就可以重新用，我看issues里面大多数人都有提这个问题。我会在后续修复版本中给出Boolean类型的props，来控制是否可以重复触发扫描。

**Comment by shifeng1993** [comment]
1.2.2 版本已添加，此类问题会在三日后关闭
